name: Automated script to run readme updater, and then push the change
#tried to learn github actions with this. 
#maybe its a fault i haven't managed to diagnose  on my part, 
#but the indentation basis of this is horrible to work with. 
#need to run it through validators and formatters just to have it work.

on:
  workflow_dispatch: #make this manually triggerable
  schedule: #uses the same chronos
    - cron: 0 0 */2 * *
jobs:
  update:
    runs-on: ubuntu-latest #github actions make a small ubuntu vm 
    permissions: #this is updating the file, so need it to have write perms
      contents: write
    steps:
    - name: load repo files
      uses: actions/checkout@v3
      
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: get the modules
      run: pip install requests
      
    - name: update the readme
      env:
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
      run: python spotifypush.py

      #checking wether there is a diff in cur and cached, if non then no push
    - name: push change to the repo
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add README.md
        if ! git diff --cached --quiet; then 
          git commit -m "Update top artists"
          git push
        else
          echo "its working alright, spotify artists not updated."
        fi 
#indentation matters quite a bit. 
