name: Automated script to run readme updater, and then push the change
  #learning github actions with this one lesgo

on: 
workflow_dispatch:
schedule: 
  - cron: '0 */6 * * *' #cron is a shortening of chronos ; this particular one calls it every 6 hours. 
    

      jobs:
        update: #this is a job named update. 
        runs_on: ubuntu-latest #github uses a small ubuntu vm for actions

        steps:
          - name: load repo files 
            uses: actions/checkout@v3

          - name: setup python 
            uses: actions/setup-python@v4
            with:
              python-version: '3.x'

          - name: get the modules
            run: pip install requests
            #os is already included into the standard install 

          - name: update the readme
            #load the secret variables 
            env: 
            SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
            SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
            SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
            run: python spotifypush.py 

            -name: push change to the repo
            run: |
              git config user.name "GitHub Action"
              git config user.email "action@github.com"
              git add README.md
              git commit -m "Update top artists"
              git push

